rules:
  default:
    merge_strategy:
      method: rebase
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts: []
        strict: true
