rules:
  default:
    merge_strategy:
      method: rebase
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts:
        - mergify/future-config-checker
        - continuous-integration/travis-ci/push
        - continuous-integration/travis-ci/pr
        strict: true
